"""
Skin database for MR-SkinChanger.

Loads character and skin data from the bundled data/game_database.json,
which is generated by scripts/build_database.py using FModel's Game.json
export.  No network calls are made.
"""

import json
from dataclasses import dataclass, field
from typing import Optional

from ._paths import BUNDLE_DIR

DB_PATH = BUNDLE_DIR / "data" / "game_database.json"

# Skin names containing any of these substrings are hidden from the UI.
SKIN_BLACKLIST = ["Cosmic Invasion"]

# Skin IDs whose trailing 3-digit part identifies them as the "original" look
# (the game stores the default skin with variant 001, and some older entries
# with variant 000).  Both are excluded from the swappable skin list.
_DEFAULT_SUFFIXES = ("001", "000")


@dataclass
class SkinInfo:
    """A single skin entry."""
    skin_id:   str        # e.g. "1055500"
    skin_name: str        # e.g. "Devil 2099"
    wiki_url:  str = ""   # kept for API compat; always empty with local DB


@dataclass
class CharacterInfo:
    """Full character entry with skins."""
    name:            str
    char_id:         str                         # e.g. "1055"
    default_skin_id: str                         # e.g. "1055001"
    skins:           list[SkinInfo] = field(default_factory=list)


class SkinDatabase:
    """
    Manages the skin/character database loaded from data/game_database.json.
    The JSON is generated by scripts/build_database.py and ships with the app.
    """

    def __init__(self) -> None:
        self.characters: dict[str, CharacterInfo] = {}
        self._load()

    # ------------------------------------------------------------------
    # Load from bundled JSON
    # ------------------------------------------------------------------

    def _load(self) -> None:
        if not DB_PATH.exists():
            print(f"[SkinDB] database not found at {DB_PATH}")
            return
        try:
            data = json.loads(DB_PATH.read_text(encoding="utf-8"))
        except Exception as exc:
            print(f"[SkinDB] failed to read database: {exc}")
            return

        for name, char_data in data.get("characters", {}).items():
            skins = [
                SkinInfo(
                    skin_id=s["skin_id"],
                    skin_name=s["skin_name"],
                )
                for s in char_data.get("skins", [])
            ]
            self.characters[name] = CharacterInfo(
                name=name,
                char_id=char_data["char_id"],
                default_skin_id=char_data["default_skin_id"],
                skins=skins,
            )

        print(f"[SkinDB] Loaded {len(self.characters)} characters from local database")

    # ------------------------------------------------------------------
    # Queries  (same interface as the old API-based version)
    # ------------------------------------------------------------------

    def get_character_names(self) -> list[str]:
        """Return sorted list of character names."""
        return sorted(self.characters.keys())

    def get_character(self, name: str) -> Optional[CharacterInfo]:
        """Look up a character by name."""
        return self.characters.get(name)

    def get_skins(self, character_name: str) -> list[SkinInfo]:
        """Return swappable skins (excludes default look and blacklisted entries)."""
        char = self.characters.get(character_name)
        if not char:
            return []
        return [
            s for s in char.skins
            if not s.skin_id.endswith(_DEFAULT_SUFFIXES)
            and not any(bl.lower() in s.skin_name.lower() for bl in SKIN_BLACKLIST)
        ]

    def get_all_skins(self, character_name: str) -> list[SkinInfo]:
        """Return all skins including the default."""
        char = self.characters.get(character_name)
        if not char:
            return []
        return list(char.skins)
